### PR TITLE
UI improvements for macOS

### PR DESCRIPTION
**Pull request by jakepetroules**
This pull request provides a number of UI enhancements, most particularly to make the application behave better according to macOS UI and UX conventions.

It resolves issues #183 and #185 while at the same time improving usability.

### CODE REVIEW

**Comment by clupprich** [comment]
This is awesome, thanks so much @jakepetroules!

**Comment by michaelblyons** [comment]
I agree this is awesome! I did notice something weird, though:

If you move the `OpenConnect.app` built by Jake's branch into the Applications directory, it breaks future builds. I think the name change in ebc0680 is interfering with the logic in `FindOpenConnect.cmake`.

**Comment by jakepetroules** [comment]
OK, I dropped the two offending commits from the PR. I plan to re-introduce the LSUIElement one later by making it runtime-configurable, though. Then you can keep your Dock icon, and I can get rid of it - everyone wins. :)

**Comment by michaelblyons** [comment]
@jakepetroules To fix the problem I was having, put this into `FindOpenConnect.cmake` just ahead of line 26. Then `OpenConnect.app` should work fine as a name.

```cmake
	set(CMAKE_FIND_APPBUNDLE NEVER)
```

**Comment by horar** [comment]
As I mentioned in #183 and #185, I don't plan make an agent from this app on macOS, because toooo many UI changes are required (may be after I finish connection code refactoring...)

**Comment by jakepetroules** [comment]
Why did you leave out several of the useful commits from this PR?

**Comment by horar** [comment]
> Why did you leave out several of the useful commits from this PR?

which one?

**Comment by jakepetroules** [comment]
There were 7 commits in here, you only merged 2 of them.

**Comment by horar** [comment]
Yep, I didn't consider them to be useful at this time - look to my above comments and comments to relevant tickets. These not merged make UI more fragile and less usable.

**Pull request closed without merging**
