### PR TITLE
OS X build and privilege elevation

### PR DESCRIPTION
**Pull request by jthiltges**
Hi openconnect-gui developers,

Here are a few patches that appear to make the OS X version build cleanly against libraries installed with brew, ask for privilege escalation if needed, and bundles the vpnc-script inside the application so it's self-contained.

These patches work for me, but I'm not an expert, particularly when it comes to OS X. Hopefully it may be useful for you. I'd also be happy to split these into separate requests if it would be helpful.

Regards,
John

Building:

* Add /usr/local/include to OS X include path
* Disable PKCS#11 features if the functions are not available

Privilege elevation:

* Attempt to re-launch the application with elevated privilege
* Use geteuid() instead of getuid() to check if we have root privileges
* Global symbol "log" in main.cpp conflicts with log() from math.h

Other:

* Include vpnc-script in the OS X application

### CODE REVIEW

**Comment by horar** [comment]
Hi John (@jthiltges) , I'm planning look to this featir for version 1.5, anyway thanks for pull request, I appreciate it. I take a quick look to this and I see u're using 'AuthorizationExecuteWithPrivileges' call that is deprecated for really long time by Apple. So, one question - did u try this on actual 10.11 without any security degradation tweaks to system settings? Thanks :smile:

**Comment by jthiltges** [comment]
Hi Horar,

Thanks for taking a look.

That's a good question. I just did a quick test after upgrading to 10.11, and it appears to work OK despite the deprecated API.

I agree that AuthorizationExecuteWithPrivileges()--and prompting for a password on every startup--is not a great solution. At best, it's a user-friendly alternative to launching the app with sudo.

Looking for options, I had run across SMJobBless(). Reworking the application to use a helper tool looks like the best direction, but is a bigger change than I feel comfortable attempting.

Best regards,
John

**Comment by horar** [comment]
Hi,
prompting for a password on every run is fine, that is a standard security rule for many apps. I agree, runnig via sudo is a pain... 
ok, I will look closer to this & I will make some test on my macbooks when I winish my open tickets, Please be patient, I will come back!
Best Regards,
Lubomir

**Comment by horar** [comment]
okey-dokey ... we moved in devel-branch, so I merged/cherry-pick elevation stuff, some changes was already implemented - so I'm closing this pull request as finished
(may be later we can play with recommended elevation approach...)

**Pull request closed without merging**
