### PR TITLE
Feature/globalprotect

### PR DESCRIPTION
**Pull request by horar**

### CODE REVIEW

**Comment by mesmaili151** [comment]
Hi,
Yesterday i updated my windows and my openconnect is deactivated.
I have a this error in log file :
2019-06-05 23:36:47 | 2f14 | Could not open C:/Users/......../AppData/Local/Temp\vpnc.log: 5

**Comment by horar** [comment]
hi, I'm sorry, can't help you based on one line from log file :/
Which app version, which system version? Do you use other VPN software?
My recommendtation is to uninstall tap-drivers and re-install openconnect-gui.

**Comment by pgross41** [comment]
@horar any thoughts on when 1.5.4 will be released with this feature?

**Comment by horar** [comment]
@pgross41 you can try snapshot build (link on main GH page) for now; yes, 1.5.4 should be released..

**Comment by att1cus86** [comment]
Hello.. I have noticed when connecting to VPNs with a 32 bit subnet mask the routing table is incorrectly populated.  The next hop address is always 1 address higher than what is needed.  I can manually change the route and VPN works fine.

**Comment by att1cus86** [comment]
Hello.. I have noticed when connecting to VPNs with a 32 bit subnet mask the routing table is incorrectly populated. The next hop address is always 1 address higher than what is needed. I can manually change the route and VPN works fine.  Is this fixed in 1.5.4?

**Comment by pgross41** [comment]
> @pgross41 you can try snapshot build (link on main GH page) for now

I installed v1.5.3-89 and it seemed like everything was successful with this at the end: 
```
ESP session established with server
ESP tunnel connected; exiting HTTPS mainloop.
``` 
But then it crashes. 

This is the only error or warning in the logs: 
```
WARNING: Server asked us to submit HIP report with md5sum 1afda59608c1541cedaa6f0b38e58239.
VPN connectivity may be disabled or limited without HIP report submission.
You need to provide a --csd-wrapper argument with the HIP report submission script.
```

I will try again once the final 1.5.4 release is available. Thank you for your effort in this tool by the way! It allows me to log into work and still have access to my local network.

**Comment by horar** [comment]
@pgross41 thank you for feeback. The true is that the app is just a simple gui on top [openconnect](https://gitlab.com/openconnect/openconnect) project and bunch ov vpnc scripts. Some things are not yet implemented in this UI. But. The best way to solve connection issues is to talk directly to openconnect project team; once it is fixed there the GUI will bundle/release it.

**Pull request merged**
